apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "org.ns" . }}
spec:
  selector: { app: backend }
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.backend.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ include "org.ns" . }}
spec:
  replicas: 1
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
        - name: backend
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef: { name: app-env }
          env:
{{- toYaml .Values.backend.env | nindent 12 }}
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 10
